Repository wecode-bootcamp-korea/fullstack1-1st-Rush-and-Lush-frontend, pull requests merged in 2021-07, with the labels that each got.

#8 [김지현] footer 레이아웃 진행 중
  src/Routes.js
  src/component/Footer/Footer.js
  src/component/Footer/Footer.scss
  src/index.js
  src/styles/common.scss
  src/styles/variables.scss
Labels: Status: Accepted

#4 [최민기] main page 구현
  package-lock.json
  package.json
  public/images/btm_slide_1.jpg
  public/images/btm_slide_2.jpg
  public/images/btn_empty.png
  public/images/btn_empty_bk.png
  public/images/btn_full.png
  public/images/btn_full_bk.png
  public/images/card.jpg
  public/images/card_1.jpg
  public/images/card_2.jpg
  public/images/card_3.jpg
  public/images/card_4.jpg
  public/images/card_5.jpg
  public/images/card_6.jpg
  public/images/img_left.jpg
  public/images/img_left_2.jpg
  public/images/img_right_btm_1.jpg
  public/images/img_right_btm_2.jpg
  public/images/img_right_btm_3.jpg
  public/images/img_right_btm_4.jpg
  public/images/img_right_up.jpg
  public/images/img_right_up_2.jpg
  public/images/mainDownArrow.png
  public/images/mainUpArrow.png
  public/images/main_slide_1.jpg
  public/images/main_slide_2.jpg
  public/images/main_slide_3.jpg
  public/images/main_slide_4.jpg
  public/images/main_slide_5.jpg
  public/images/main_slide_6.jpg
  public/images/side_slide_1.jpg
  public/images/side_slide_2.jpg
  public/images/side_slide_3.jpg
  public/images/side_slide_4.jpg
  public/itemCardData.json
  public/mainSlideData.json
  src/pages/Detail/Detail.js
  src/pages/Main/BtmSlide/BtmSlide.js
  src/pages/Main/BtmSlide/BtmSlide.scss
  src/pages/Main/GridImg/GridImg.js
  src/pages/Main/GridImg/GridImg.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainSlide/ItemCard/Card/Card.js
  src/pages/Main/MainSlide/ItemCard/ItemCard.js
  src/pages/Main/MainSlide/ItemCard/ItemCard.scss
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/MainSlide/MainSlide.scss
  src/pages/Main/MainSlide/SideSlide/SideSlide.js
  src/pages/Main/MainSlide/SideSlide/SideSlide.scss
Labels: Status: 리뷰 요청

#11 [최민기] 디테일 페이지 구현
  public/images/card_1.jpg
  public/itemInfoData.json
  src/Routes.js
  src/pages/Detail/Banner/Banner.js
  src/pages/Detail/Banner/Banner.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/DetailNav/DetailNav.js
  src/pages/Detail/DetailNav/DetailNav.scss
  src/pages/Detail/Info/Info.js
  src/pages/Detail/Info/Info.scss
  src/pages/Detail/ItemDetail/ItemDetail.js
  src/pages/Detail/ItemDetail/ItemDetail.scss
  src/pages/Detail/ItemTab/ItemTab.js
  src/pages/Detail/ItemTab/ItemTab.scss
  src/pages/Detail/ItemTab2/ItemTab2.js
  src/pages/Detail/ItemTab2/ItemTab2.scss
  src/pages/Detail/Review/Review.js
  src/pages/Detail/Review/Review.scss
Labels: Status: 리뷰 요청

#12 [김지현] Footer 수정 사항 추가
  src/component/Footer/Footer.scss
Labels: Status: 리뷰 요청

#3 [신수호] 로그인 레이아웃 기능 구현 완료
  package.json
  src/Routes.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/NonMembersLogin.js
  src/pages/Login/NonMembersLogin.scss
  src/pages/Login/component/LoginPage.js
  src/pages/Login/component/LoginPage.scss
Labels: Status: Conflict 해결 요청, Status: 리뷰 요청

#6 [안진근] list page 레이아웃 완료
  package-lock.json
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/component/ListNav/ListNavCategory.js
  src/pages/List/component/ListNav/ListNavCategory.scss
  src/pages/List/component/ListNav/ListNavCategoryList.js
  src/pages/List/component/ListNav/ListNavCategoryListData.js
  src/pages/List/component/ListNav/ListNavTitle.js
  src/pages/List/component/ListNav/ListNavTitle.scss
  src/pages/List/component/ListPageHeader.js
  src/pages/List/component/ListPageHeader.scss
  src/pages/List/component/ListProductItem.js
  src/pages/List/component/ListProductItem.scss
  src/pages/List/component/ListProductItemData.js
  src/pages/List/component/ListTagButton.js
  src/pages/List/component/ListTagButton.scss
Labels: Status: 리뷰 요청, Status: 수정 요청

#10 [신수호] 회원가입 페이지 레이아웃 구현완료 인풋창 활성화 기능 완료
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: Conflict 해결 요청, Status: 리뷰 요청

#16 [최민기] 디테일 페이지 상하단 margin 추가
  src/pages/Detail/Detail.scss
Labels: Status: 리뷰 요청

#21 [최민기] Footer 위 아이콘 모음 추가
  src/component/Footer/Footer.js
  src/component/Footer/Footer.scss
Labels: Status: 리뷰 요청

#20 [최민기] 리스트 페이지 스타일 수정
  src/pages/List/component/ListNav/ListNavTitle.scss
  src/pages/List/component/ListPageHeader.scss
  src/pages/List/component/ListProductItem.js
Labels: Status: 리뷰 요청

#18 [최민기] 메인페이지 스타일 추가 수정
  src/pages/Main/BtmSlide/BtmSlide.js
  src/pages/Main/BtmSlide/BtmSlide.scss
  src/pages/Main/GridImg/GridImg.js
  src/pages/Main/GridImg/GridImg.scss
  src/pages/Main/Main.scss
  src/pages/Main/MainSlide/ItemCard/ItemCard.js
  src/pages/Main/MainSlide/ItemCard/ItemCard.scss
Labels: Status: 리뷰 요청

#19 [최민기] 검색창 modal 제작
  src/component/Nav/Modal/Modal.js
  src/component/Nav/Modal/Modal.scss
  src/component/Nav/Nav.js
Labels: Status: 리뷰 요청

#22 [최민기] 푸터 아이콘 스크롤 오류 해결
  src/component/Footer/Footer.scss
Labels: Status: 리뷰 요청

#27 [김지현] Router 파일 경로 수정
  src/Routes.js
Labels: Status: 리뷰 요청

#26 [김지현] Footer 리팩토링 및 컴포넌트 분리 진행 중
  src/component/Footer/Footer.js
  src/component/Footer/Footer.scss
  src/component/Footer/FooterSubWrap.js
  src/component/Footer/FooterSubWrapRight.js
  src/component/Footer/FooterUpperImage.js
  src/component/Footer/data.js
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#30 [신수호] 로그인 페이지 리팩토링 완료
  src/pages/Login/Login.js
  src/pages/Login/NonMembersLogin.js
  src/pages/Login/NonMembersLogin.scss
  src/pages/Login/component/LoginPage.js
  src/pages/Login/component/LoginPage.scss
  src/pages/Login/component/MemberNav.js
  src/pages/Login/component/MemberNav.scss
  src/pages/Login/component/NonMembersLogin.js
  src/pages/Login/component/NonMembersLogin.scss
Labels: Status: 수정 요청
